#define tFL 
#define tEGAL 
#define tPO 
#define tPF 
#define tSOU 
#define tADD 
#define tDIV 
#define tMUL 
#define tERROR 
#define tNB 
#define tKEYWORD 
#define tMAIN
#define tCONST 
#define tINTVAR 
#define tSEP 
#define tENDLINE 
#define tENDINST 
#define tPRINTF
#define tEXP