#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri May 15 12:18:07 CEST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim pipeline_tb_behav -key {Behavioral:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view /home/mougnibas/Bureau/4IR/S2/projet-systeme-info/VHDL/projet-systeme-info/pipeline_tb_behav.wcfg -log simulate.log"
xsim pipeline_tb_behav -key {Behavioral:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view /home/mougnibas/Bureau/4IR/S2/projet-systeme-info/VHDL/projet-systeme-info/pipeline_tb_behav.wcfg -log simulate.log

