#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Apr 25 12:09:44 CEST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim DATA_MEM_tb_behav -key {Behavioral:sim_1:Functional:DATA_MEM_tb} -tclbatch DATA_MEM_tb.tcl -log simulate.log"
xsim DATA_MEM_tb_behav -key {Behavioral:sim_1:Functional:DATA_MEM_tb} -tclbatch DATA_MEM_tb.tcl -log simulate.log

